version: '3.1'
services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "7070:80"
    volumes:
      - ./code:/code
      - ./html:/var/www/html
    networks:
      - web-tier
      - service-tier
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    container_name: db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - "${DB_LOCAL_PATH}:/var/lib/mysql"
    networks:
      - service-tier
    dns:
      - 8.8.8.8
      - 8.8.4.4
networks:
  web-tier:
  service-tier:

