version: '3.1'
services:
  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${WP_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${WP_DB_NAME}"
      MYSQL_USER: "${WP_DB_USER}"
      MYSQL_PASSWORD: "${WP_DB_PASSWORD}"
    volumes:
      - "${DB_LOCAL_PATH}:/var/lib/mysql"
    networks:
      - db-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${WP_DB_NAME}"
      WORDPRESS_DB_USER: "${WP_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WP_DB_PASSWORD}"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./code:/code
      - ./html:/var/www/html
    networks:
      - web-network
      - db-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
networks:
  web-network:
  db-network:
